# Generated by Django 4.2.16 on 2024-12-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_caption_notice_ncaption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='Nuser',
            new_name='user',
        ),
    ]
